CREATE TABLE IF NOT EXISTS court_day_notice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_date TIMESTAMP(6) NOT NULL,
    notice TEXT NOT NULL,
    notice_date DATE NOT NULL,
    partner_id BIGINT NOT NULL,
    update_date TIMESTAMP(6)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ukblnqq343xnlteh6osdra01fnn'
          AND conrelid = 'court_day_notice'::regclass
    ) THEN
        ALTER TABLE court_day_notice
            ADD CONSTRAINT ukblnqq343xnlteh6osdra01fnn UNIQUE (partner_id, notice_date);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS cummunity_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active_yn VARCHAR(1) NOT NULL,
    create_date TIMESTAMP(6) NOT NULL,
    display_order INTEGER NOT NULL,
    title VARCHAR(120) NOT NULL,
    update_date TIMESTAMP(6),
    url VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS favorite_partner (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_date TIMESTAMP(6) NOT NULL,
    partner_id BIGINT NOT NULL,
    username VARCHAR(20) NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uk3bq4tucr18cfjbiktabay4mp0'
          AND conrelid = 'favorite_partner'::regclass
    ) THEN
        ALTER TABLE favorite_partner
            ADD CONSTRAINT uk3bq4tucr18cfjbiktabay4mp0 UNIQUE (username, partner_id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS game_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    court_id BIGINT NOT NULL,
    game_result VARCHAR(20),
    game_end VARCHAR(2) DEFAULT 'N',
    game_date DATE,
    time_slot VARCHAR(20),
    create_date TIMESTAMP NOT NULL DEFAULT NOW(),
    update_date TIMESTAMP
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_game_result_court'
          AND conrelid = 'game_result'::regclass
    ) THEN
        ALTER TABLE game_result
            ADD CONSTRAINT fk_game_result_court
            FOREIGN KEY (court_id) REFERENCES court(id) ON DELETE CASCADE;
    END IF;
END $$;
